.Dd August 13, 2018
.\"  Patch this in our groff's mdoc.local
.ds volume-operating-system Arch Linux
.ds default-operating-system Arch Linux
.Os Arch Linux
.Dt checkpkg 1
.Sh NAME
.Nm checkpkg
.Nd shows difference between a build package and the current version
.Sh SYNOPSIS
.Nm checkpkg
checkpkg compares the current build package with the previous version and ...
.Sh DESCRIPTION
.Sh BUGS
Bugs? You must be kidding; there are no bugs in this software. But if we happen
to be wrong, send us an email with as much detail as possible to
arch-projects@archlinux.org
.Sh AUTHORS
.An Aaron Griffin <aaronmgriffin@gmail.com>
.An Pierre Schmitz <pierre@archlinux.de>
.An Lukas Fleischer <archlinux@cryptocrack.de>
.An Luke Shumaker <lukeshu@parabola.nu>
